version: '3.8'
services:
  stats-server:
    build: stats
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:15.2-alpine
    container_name: stats-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main-service
    container_name: main-server
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVICE_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_main
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  ewm-db:
    image: postgres:15.2-alpine
    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
