version: '3.1'
services:
  stats-server:
    build: stats-service
    container_name: stats-service
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      #      - TZ=Europe/Moscow
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/ewm_stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres:15.2-alpine
    container_name: stats-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
