FROM amazoncorretto:11-alpine-jdk
LABEL authors="gleb"
COPY library/target/library-0.0.1-SNAPSHOT.jar library.jar
COPY server/target/server-0.0.1-SNAPSHOT.jar server.jar
COPY client/target/client-0.0.1-SNAPSHOT.jar client.jar